eureka:
  client:
    fetch-registry: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: members
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/Member/**
        - id: clubs
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/Club/**